const dataStructureGroups = {
    actors: {
        relations: ["tags", "nationalities"],
        nameType: "name", // name or title
        topInfos: ["movies", "rating"],
        orders: [
            "name",
            "name_reversed",
            "rating",
            "rating_reversed",
            "birthday",
            "birthday_reversed",
            "movies",
            "movies_reversed",
        ],
        defaultOrder: "name",
        thumbnailSize: "Portrait", // Portrait, Square, Landscape
        itemLabel: "actor",
        itemGroup: "actors",
        APIfetchAll: "/api/actor/all",
        APIfetchSearch: "/api/actor/search",
    },
    movies: {
        relations: ["categories", "tags", "nationalities"],
        nameType: "title",
        topInfos: ["cast", "rating"],
        orders: [
            "created_at",
            "title",
            "title_reversed",
            "rating",
            "rating_reversed",
            "older",
            "release",
            "release_reversed",
        ],
        defaultOrder: "created_at",
        thumbnailSize: "Landscape",
        itemLabel: "movie",
        itemGroup: "movies",
        APIfetchAll: "/api/movie/all",
        APIfetchSearch: "/api/movie/search",
    },
    studios: {
        relations: ["movies", "nationalities"], // add categories? actors?
        nameType: "name",
        topInfos: ["movies"],
        orders: ["name", "name_reversed", "movies", "movies_reversed"],
        defaultOrder: "name",
        thumbnailSize: "Landscape", // Square ?
        itemLabel: "studio",
        itemGroup: "studios",
        APIfetchAll: "/api/studio/all",
        APIfetchSearch: "/api/studio/search",
    },
    distributions: {
        relations: ["movies", "nationalities"], // add categories? actors?
        nameType: "name",
        topInfos: ["movies"],
        orders: ["name", "name_reversed", "movies", "movies_reversed"],
        defaultOrder: "name",
        thumbnailSize: "Landscape",
        itemLabel: "distribution",
        itemGroup: "distributions",
        APIfetchAll: "/api/distribution/all",
        APIfetchSearch: "/api/distribution/search",
    },
    categories: {
        relations: ["movies"],
        nameType: "name",
        topInfos: ["movies"],
        orders: ["name", "name_reversed", "movies", "movies_reversed"],
        defaultOrder: "name",
        thumbnailSize: "Landscape",
        itemLabel: "category",
        itemGroup: "categories",
        APIfetchAll: "/api/category/all",
        APIfetchSearch: "/api/category/search",
    },
    tags: {
        relations: ["movies", "actors"],
        nameType: "name",
        topInfos: ["movies"],
        orders: [
            "name",
            "name_reversed",
            "movies",
            "movies_reversed",
            "actors",
            "actors_reversed",
        ],
        defaultOrder: "name",
        thumbnailSize: "Landscape",
        itemLabel: "tag",
        itemGroup: "tags",
        APIfetchAll: "/api/tag/all",
        APIfetchSearch: "/api/tag/search",
    },
    nationalities: {
        relations: ["studios", "distributions", "actors"],
        nameType: "name",
        topInfos: ["actors", "studios"],
        orders: [
            "name",
            "name_reversed",
            "studios",
            "studios_reversed",
            "actors",
            "actors_reversed",
        ],
        defaultOrder: "actors",
        thumbnailSize: "Landscape",
        itemLabel: "nationality",
        itemGroup: "nationalities",
        APIfetchAll: "/api/nationality/all",
        APIfetchSearch: "/api/nationality/search",
    },
};

export default dataStructureGroups;
